### ISSUE TITLE
Initialize client with custom host

### ISSUE THREAD

**Issue by michalpaukert** [contentful-userland/contentful-wizard#15]
I want be able to specify my custom host as it is possible in ContentfulClientApi https://contentful.github.io/contentful.js/contentful/4.5.0/contentful.html#.createClient
My proposal is in #14

**Comment by michalpaukert** [comment]
Issue is resolved, could you publish new version?

**Comment by stefanjudis** [comment]
I don't have publishing access. @Bloomca could we transfer ownership and npm access of this package?

**Comment by Bloomca** [comment]
@stefanjudis what is your npm username? Same, `stefanjudis`?

**Comment by stefanjudis** [comment]
@Bloomca jup. :)

**Comment by Bloomca** [comment]
I added you!

**Comment by stefanjudis** [comment]
@michalpaukert I published `0.0.1`. Let me know if that works. 

Thanks @Bloomca! 🙇

**Comment by michalpaukert** [comment]
@stefanjudis thank you it works.
